### ISSUE TITLE
[1.11-1.7.5] - Forge requirement change?

### ISSUE THREAD

**Issue by shortybsd** [MinecraftModDevelopmentMods/HempFarmer#30] opened 2017-01-11 00:37 UTC
We run Forge 2199 for 1.11. In the future could you update the forge requirement for current version and newer rather than a specific version?

**Comment by EPIICTHUNDERCAT** [comment] 2017-01-11 00:40
whats wrong? that doesn't really tell me what the issue is.

**Comment by shortybsd** [comment] 2017-01-11 01:25
Sorry, it called for a specific version of forge which was way older than my current version. I believe 2162 or something like that, I already deleted the crashlog.

**Comment by shortybsd** [comment] 2017-01-11 01:26
Give me a few, I will reload the mod on my server and grab the crashlog exactly. Currently people on it lol.

**Comment by EPIICTHUNDERCAT** [comment] 2017-01-11 01:28
shouldn't have? for 1.11?

**Comment by EPIICTHUNDERCAT** [comment] 2017-01-11 01:28
ill look into it. the 1.11 version is not on github

**Comment by EPIICTHUNDERCAT** [comment] 2017-01-11 01:29
version = "1.11-13.19.1.2189"

**Comment by EPIICTHUNDERCAT** [comment] 2017-01-11 01:29
this is what im using which is recommended forge for 1.11.

**Comment by EPIICTHUNDERCAT** [comment] 2017-01-11 01:30
modders try to stick with the recommended version of forge so I won't be updating to latest any time soon.

**Comment by shortybsd** [comment] 2017-01-11 01:31
"the 1.11 version is not on github" It was because I downloaded it an hour ago. I run forge 2199 which if you require 2189 or newer there would be no issues. Hang on i will load it up right now and give you the exact error.

**Comment by shortybsd** [comment] 2017-01-11 01:32
Never seen a mod yet that required a specific version of forge, only a range example a minimal recommended version example 2180 ... meaning anything higher than that would work. I am a modder/developer myself as well.

**Comment by shortybsd** [comment] 2017-01-11 01:34
hempfarmer-1.11-1.7.5.jar

**Comment by EPIICTHUNDERCAT** [comment] 2017-01-11 01:35
show me the error. what I meant by "modders try to stick with the recommended version of forge so I won't be updating to latest anytime soon." is that I don't use latest versions in my IDE, especially 1.11 as it is unstable. my mod is not requiring 1.11-13.19.1.2189 specifically or at least it shouldn't be

**Comment by SeqSEE** [comment] 2017-01-11 01:42
https://github.com/MinecraftModDevelopment/HempFarmer/blob/master/update.json

That might be the issue?

**Comment by shortybsd** [comment] 2017-01-11 01:45
[19:44:35] [Client thread/ERROR]: The mod hempfarmer (HempFarmer) requires mods [Forge] to be available
[19:44:35] [Client thread/ERROR]: Mod hempfarmer (HempFarmer) requires [Forge@[12.17.0.1976,)]

It isn't a range but an exact version of forge and nothing else.

**Comment by shortybsd** [comment] 2017-01-11 01:47
I'll go through your source and find the issue, give me a second.

**Comment by shortybsd** [comment] 2017-01-11 01:48
https://github.com/MinecraftModDevelopment/HempFarmer/blob/master/src/main/java/com/shruglabs/hempfarmer/Reference.java#L5

**Comment by SeqSEE** [comment] 2017-01-11 01:49
Also
https://github.com/MinecraftModDevelopment/HempFarmer/blob/master/src/main/java/com/shruglabs/hempfarmer/Reference.java

**Comment by EPIICTHUNDERCAT** [comment] 2017-01-11 01:50
thank you for making me aware of the issue. ill post a hotfix momentarily

**Comment by SeqSEE** [comment] 2017-01-11 01:50
On my phone and on my way home. I'll fix that within a couple hours.

**Comment by shortybsd** [comment] 2017-01-11 01:53
Awesome, you guys rock! Just make a requirement on mod info site which forge is required and pull out the dependency line. Poof :)

**Comment by shortybsd** [comment] 2017-01-14 20:02
Any update on fixing that error?

**Comment by cyberpunkbln** [comment] 2017-04-06 23:00
Hi,
is the bugfixing on the way? I mean the mod is not usable on 1.11.2. I it not possible to make a quick fix that the mod don't use a public static final var? mcmod.info don't functioned.
thx

**Comment by EPIICTHUNDERCAT** [comment] 2017-04-07 16:25
sorry I have not, Ill try to get this fixed as soon as possible!!!

**Comment by cyberpunkbln** [comment] 2017-04-07 18:02
hello, thx

**Comment by EPIICTHUNDERCAT** [comment] 2017-04-09 04:18
Should be fixed in 1.7.6, i launched just fine. please let me know if this is still an issue, closing for now.

**Closed by EPIICTHUNDERCAT** 2017-04-09 04:18 UTC
Labels: bug
